### ISSUE TITLE
Strong name sign the assembly.

### ISSUE THREAD

**Issue by MitchBodmer** [MitchBodmer/serilog-sinks-testcorrelator#37]

**Comment by MitchBodmer** [comment]
Not supported in .net core.

**Comment by SimonCropp** [comment]
strong naming is supported in netcore

**Comment by MitchBodmer** [comment]
Yep, you're 100% right. At the time that comment was made it wasn't recommended, but since then it's become first class. I'll sign it.

**Comment by SimonCropp** [comment]
yeah i wish strong naming would die. but i have given up fighting against it

**Comment by MitchBodmer** [comment]
Yep. Not a hill I'm going to die on.

The [signed version](https://www.nuget.org/packages/Serilog.Sinks.TestCorrelator/3.2.0) is up on NuGet now. It should be indexed soon.

**Comment by SimonCropp** [comment]
Awesome. Thanks
