### ISSUE TITLE
Any easy way to get back to the POCO from the LogEventPropertyValue?

### ISSUE THREAD

**Issue by lesscodetxm** [MitchBodmer/serilog-sinks-testcorrelator#57]
The TestCorrelator is exactly what we've been looking for to validate our unit tests, but we're missing one last step. We use Serilog's ForContext to add destructured POCOs to our logs. We can see the properties of those objects in the LogEventPropertyValues returned by the TestCorrelator, but how can we easily reconstruct the original POCO?

**Comment by MitchBodmer** [comment]
Are you're using the destructuring operator? Unfortunately, before any sinks receive the log event the object will have been destructured, so it would be up to you to reconstitute the objects.

That being said, I'd be interested in understanding your use case here. I usually wouldn't suggest reconstituting the objects in order to test your log output. Since the sinks will never see the reconstituted objects, your tests would not only be verifying the log output but also the extra code you wrote to recreate the objects. I'd hazard that writing tests against the LogEvents and it's properties would be less fragile and more likely to catch regressions.

**Comment by lesscodetxm** [comment]
We have an existing `EventLog` structure that we're writing to a database table via Entity Framework. In unit tests we're currently using an in-memory version of the EF context, so we can query the logs via an `IQueryable<EventLog>`. We only currently do this for certain special types of event (that we need to be able to easily query for reporting purposes), other logging (eg debug or ASP.NET logging) goes to a file or the console. . This make it cumbersome to "weave" logging info together over a specific time period in order to diagnose problems.

What we're aiming to do is centralize all of our logging in Elasticsearch so we can see all of the context together (across services and clients, for all event types).

We're using Serilog to standardize how we log, and when we want to log our old EventLog object, we use "ForContext":

Log.ForContext("EventLog", eventLog, true)

This gives us a `logevent` document that contains attributes such as `fields.EventLog.Property`, and we can craft an ElasticLinq `IQueryable<logevent>` to search those logs in ES, and generate `logevent` POCOs eg:

```
ElasticContext.Query<logevent>().Take(n).Where(e => e.fields.EventLog.EventMessage.Contains("blah"))
```

Our reporting business logic is can now abstracted in such a way that we can hand it an `IQueryable<logevent>` instead of an `IQueryable<EventLog>` to generate the report (this change is much simpler than converting all our reports and unit tests to use a native Elasticsearch query paradigm).

So, in unit/integration tests, we just the TestCorrelator sink instead of the ES one, but for reporting tests we need to be able to reconstitute an `IQueryable<logevent>` from the TestCorrelator, and this would also involve "restructuring" the original `EventLog` objects inside `logevent` POCOs.

This is how we're doing that right now:

```
                var logHistory = TestCorrelator.GetLogEventsFromContextGuid(logContext.Guid)
                    .Select(e => e.Properties["EventLog"])
                    .OfType<StructureValue>()
                    .Select(AsSerilogStructureValue<EventLog>)
                    .Select(e => new logevent { fields = new SerilogFields { EventLog = e }, message = e.EventMessage })
                    .AsQueryable();

        public static T AsSerilogStructureValue<T>(StructureValue value) where T : new()
        {
            var @object = new T();

            if (value != null)
            {
                var type = typeof(T);
                foreach (var property in value.Properties)
                {
                    var propertyInfo = type.GetProperty(property.Name);

                    var propertyScalarValue = property.Value as ScalarValue;
                    var propertyValue = propertyScalarValue?.Value;

                    propertyInfo.SetValue(@object, propertyValue);
                }
            }

            return @object;
        }

```

Which is not too bad, but if there's a cleaner way...

**Comment by MitchBodmer** [comment]
Unfortunately I don't think there's a better way of doing that.

You _might_ think about creating the queryable without the TestCorrelator all together though. If what you're really testing is whether or not your "reporter" does the right thing when given a specific queryable, it might be better if you create those queryables by hand in the test, as opposed to generating them with some other method's logs. Just food for thought.

**Comment by lesscodetxm** [comment]
No, you're right - we do have unit tests for reporting that generate logs directly and pass those into the reporting components. But we also have a bunch of integration tests that orchestrate several components that all log information separately, and that info gets queried and aggregated by reporting components. These are the tests where we're using the above mechanism. We may eventually revisit and refactor those tests, but for now we just want them to stay green while we're sorting out our cleaner logging infrastructure :-)
TestCorrelator is really helping us out with this - thanks for the help.
