### ISSUE TITLE
Log messages are shared between instances

### ISSUE THREAD

**Issue by LyubomirStoimchev** [MitchBodmer/serilog-sinks-testcorrelator#62]
I'm creating 2 separate logger instances (I'm not using the static logger provided by serilog) and in the constructor I'm creating the context "ctx = TestCorrelator.CreateContext();".

I log 2 messages for each logger, but when I try to get the count of messages for the specific context by guid, the returned count is 4. Is this a normal behavior?

The guids of the contexts are not the same:
Log.Logger.ctx.Guid
{e11338c2-157c-49c8-af02-e72fd2d95c02}
Log.GlobalLogger.ctx.Guid
{91bd0e9a-5df4-4795-9185-fb5de8f82aa8}

**Comment by MitchBodmer** [comment]
Yes that is expected. Any logger that emits an event to the TestCorrelator within the context you establish will be returned when you get the log events from that context. If you're setting up the context in your constructor, and then never disposing it, everything that runs after that point will be within that context.

This sink isn't for correlating log events with the logger that emitted them. That can be accomplished with something like the [ObservableSink](https://github.com/serilog/serilog-sinks-observable). This sink's purpose is to correlate log events to a specific thread of execution.
