### ISSUE TITLE
Can't get logs from controller

### ISSUE THREAD

**Issue by kusza6** [MitchBodmer/serilog-sinks-testcorrelator#63]
Hello!
First of all, thank you for great tool, done some good test automation with this already :).

However I have problem now with getting logs out from controller to TestCorrelator.

From test I'm creating logger and then my test application. Then I am doing call to weatherforecast controller where I am logging some stuff. It's correctly logged into file but testCorrelator is not catching anything.

Is it somehow possible to catch things from controller? 

Here is code example: https://github.com/kusza6/TestCorrelatorProblem

Thank you in advance for any advices :)

**Comment by MitchBodmer** [comment]
This sink uses `AsyncLocal`s to hold the context through async boundaries. The `TestServer` you're using does not preserve `AsyncLocal` values by default. Set the [`PreserveExecutionContext`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.testhost.testserver.preserveexecutioncontext?view=aspnetcore-5.0) property of the `TestServer` to true.
