### ISSUE TITLE
LogContext.Push LogEvents dont appear in TestCorrelator

### ISSUE THREAD

**Issue by WattsC-90** [MitchBodmer/serilog-sinks-testcorrelator#67]
Hi,
I have been writing some tests but seem to have run into an issue where the code under test calls `LogContext.Push(..)` to add some properties/extra info, however, the event logged out using this returned context doesnt appear in the `TestCorrelator.GetLogEventsFromCurrentContext()` returned IEnumerable.

I have been round the houses trying different methods from the tests in this repo, so any pointers/help would be great!

In the Constructor:
```
logger = new LoggerConfiguration().WriteTo.Sink(new TestCorrelatorSink()).CreateLogger();
```

The test method:

```
            // Arrange
            using (TestCorrelator.CreateContext())
            {
                var defaultContext = new DefaultHttpContext
                {
                    Response =
                    {
                        Body = new MemoryStream()
                    },
                    Request =
                    {
                        Path = "/"
                    }
                };

                // Act
                await sut.InvokeAsync(defaultContext);

                // Assert
                IEnumerable<LogEvent>? events = TestCorrelator.GetLogEventsFromCurrentContext();
```

Code under test:

```
            logger.Information("hi"); // gets logged
            using (LogContext.Push(CreateProperties()))
            {
                logger.Debug("Request to path {path} complete.", path); // doesn't get logged.
            }
```

**Comment by MitchBodmer** [comment]
Your logger isn't configured to collect Debug log events. Check out the [Serilog wiki](https://github.com/serilog/serilog/wiki/Configuration-Basics#minimum-level).
