### ISSUE TITLE
v4 incombatility with serilog-settings-configuration

### ISSUE THREAD

**Issue by sreejith-kulamgarath** [MitchBodmer/serilog-sinks-testcorrelator#76]
The following code was working with the previous version of TestCorrelator (3.2.0), but it is failing with v4.

Here is the code.

```
var configuration = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile(path: "appsettings.Test.json", optional: false, reloadOnChange: true)
            .Build();

const string message = "An event.";
using var context = TestCorrelator.CreateContext();

Log = new LoggerConfiguration().ReadFrom.Configuration(configuration).CreateLogger();

// Act
Log.Information(message);

// Assert
var logEvent = TestCorrelator.GetLogEventsFromCurrentContext().Single();
Assert.Equal(message, logEvent.MessageTemplate.Text);
```

If I replace ReadFrom.Configuration with this line, the code above works.

```
Log = new LoggerConfiguration().WriteTo.TestCorrelator().CreateLogger();
```

Here is my appsettings.Test.json

```
{
  "Serilog": {
    "Using": [
      "Serilog.Sinks.TestCorrelator"
    ],
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "TestCorrelator",
      }
    ],
    "Enrich": [
      "FromLogContext"
    ],
    "Properties": {
      "Application": "Logging.Tests"
    }
  }
}

```

**Comment by MitchBodmer** [comment]
What about it is failing?

**Comment by sreejith-kulamgarath** [comment]
The Assert fails. `TestCorrelator.GetLogEventsFromCurrentContext()` does not return any log events when we do `.ReadFrom.Configuration(configuration)`.

**Comment by MitchBodmer** [comment]
This is almost certainly because I added parameters to the `WriteTo.TestCorrelator` methods. As a workaround you can try passing an empty array as the `ids` parameter.

I think this is actually a "bug" or at least a missing feature from the Configuration library. I can comment in the other issue.

**Comment by sreejith-kulamgarath** [comment]
Modifying the appsettings file to the following worked. Thank you. Probably the ids field should have a default value of an empty array.

```
"WriteTo": [
      {
        "Name": "TestCorrelator",
        "Args": {
          "ids": []
        }
      }
    ],
```

**Comment by MitchBodmer** [comment]
It's a `params` array so it does have that default. The configuration library just doesn't detect that quite yet. I've commented over there so they can make the fix when they have time.
